STANDARD_THEMES = {
    "cosmo": {
        "type": "light",
        "colors": {
            "primary": "#2780e3",
            "secondary": "#7E8081",
            "success": "#3fb618",
            "info": "#9954bb",
            "warning": "#ff7518",
            "danger": "#ff0039",
            "light": "#F8F9FA",
            "dark": "#373A3C",
            "bg": "#ffffff",
            "fg": "#373a3c",
            "selectbg": "#7e8081",
            "selectfg": "#ffffff",
            "border": "#ced4da",
            "inputfg": "#373a3c",
            "inputbg": "#fdfdfe",
            "active": "#efefef",
        },
    },
    "flatly": {
        "type": "light",
        "colors": {
            "primary": "#2c3e50",
            "secondary": "#95a5a6",
            "success": "#18bc9c",
            "info": "#3498db",
            "warning": "#f39c12",
            "danger": "#e74c3c",
            "light": "#ECF0F1",
            "dark": "#7B8A8B",
            "bg": "#ffffff",
            "fg": "#212529",
            "selectbg": "#95a5a6",
            "selectfg": "#ffffff",
            "border": "#ced4da",
            "inputfg": "#212529",
            "inputbg": "#ffffff",
            "active": "#e2e2e2",
        },
    },
    "litera": {
        "type": "light",
        "colors": {
            "primary": "#4582ec",
            "secondary": "#adb5bd",
            "success": "#02b875",
            "info": "#17a2b8",
            "warning": "#f0ad4e",
            "danger": "#d9534f",
            "light": "#F8F9FA",
            "dark": "#343A40",
            "bg": "#ffffff",
            "fg": "#343a40",
            "selectbg": "#adb5bd",
            "selectfg": "#ffffff",
            "border": "#bfbfbf",
            "inputfg": "#343a40",
            "inputbg": "#fff",
            "active": "#e5e5e5",
        },
    },
    "minty": {
        "type": "light",
        "colors": {
            "primary": "#78c2ad",
            "secondary": "#f3969a",
            "success": "#56cc9d",
            "info": "#6cc3d5",
            "warning": "#ffce67",
            "danger": "#ff7851",
            "light": "#F8F9FA",
            "dark": "#343A40",
            "bg": "#ffffff",
            "fg": "#5a5a5a",
            "selectbg": "#f3969a",
            "selectfg": "#ffffff",
            "border": "#ced4da",
            "inputfg": "#696969",
            "inputbg": "#fff",
            "active": "#e5e5e5",
        },
    },
    "lumen": {
        "type": "light",
        "colors": {
            "primary": "#158cba",
            "secondary": "#919191",
            "success": "#28b62c",
            "info": "#75caeb",
            "warning": "#ff851b",
            "danger": "#ff4136",
            "light": "#F6F6F6",
            "dark": "#555555",
            "bg": "#ffffff",
            "fg": "#555555",
            "selectbg": "#919191",
            "selectfg": "#ffffff",
            "border": "#ced4da",
            "inputfg": "#555555",
            "inputbg": "#fff",
            "active": "#e5e5e5",
        },
    },
    "sandstone": {
        "type": "light",
        "colors": {
            "primary": "#325D88",
            "secondary": "#8e8c84",
            "success": "#93c54b",
            "info": "#29abe0",
            "warning": "#f47c3c",
            "danger": "#d9534f",
            "light": "#F8F5F0",
            "dark": "#3E3F3A",
            "bg": "#ffffff",
            "fg": "#3e3f3a",
            "selectbg": "#8e8c84",
            "selectfg": "#ffffff",
            "border": "#ced4da",
            "inputfg": "#6E6D69",
            "inputbg": "#fff",
            "active": "#e5e5e5",
        },
    },
    "yeti": {
        "type": "light",
        "colors": {
            "primary": "#008cba",
            "secondary": "#707070",
            "success": "#43ac6a",
            "info": "#5bc0de",
            "warning": "#e99002",
            "danger": "#f04124",
            "light": "#EEEEEE",
            "dark": "#222222",
            "bg": "#ffffff",
            "fg": "#222222",
            "selectbg": "#707070",
            "selectfg": "#ffffff",
            "border": "#cccccc",
            "inputfg": "#222222",
            "inputbg": "#fff",
            "active": "#e5e5e5",
        },
    },
    "pulse": {
        "type": "light",
        "colors": {
            "primary": "#593196",
            "secondary": "#69676E",
            "success": "#13b955",
            "info": "#009cdc",
            "warning": "#efa31d",
            "danger": "#fc3939",
            "light": "#F9F8FC",
            "dark": "#17141F",
            "bg": "#ffffff",
            "fg": "#444444",
            "selectbg": "#69676e",
            "selectfg": "#ffffff",
            "border": "#cbc8d0",
            "inputfg": "#444444",
            "inputbg": "#fdfdfe",
            "active": "#e5e5e5",
        },
    },
    "united": {
        "type": "light",
        "colors": {
            "primary": "#e95420",
            "secondary": "#aea79f",
            "success": "#38b44a",
            "info": "#17a2b8",
            "warning": "#efb73e",
            "danger": "#df382c",
            "light": "#E9ECEF",
            "dark": "#772953",
            "bg": "#ffffff",
            "fg": "#333333",
            "selectbg": "#aea79f",
            "selectfg": "#ffffff",
            "border": "#ced4da",
            "inputfg": "#333333",
            "inputbg": "#fff",
            "active": "#e5e5e5",
        },
    },
    "morph": {
        "type": "light",
        "colors": {
            "primary": "#378DFC",
            "secondary": "#aaaaaa",
            "success": "#43cc29",
            "info": "#5B62F4",
            "warning": "#FFC107",
            "danger": "#E52527",
            "light": "#F0F5FA",
            "dark": "#212529",
            "bg": "#D9E3F1",
            "fg": "#7B8AB8",
            "selectbg": "#aaaaaa",
            "selectfg": "#FBFDFF",
            "border": "#B9C7DA",
            "inputfg": "#7F8EBA",
            "inputbg": "#F0F5FA",
            "active": "#C3CCD8",
        },
    },
    "journal": {
        "type": "light",
        "colors": {
            "primary": "#eb6864",
            "secondary": "#aaaaaa",
            "success": "#22b24c",
            "info": "#336699",
            "warning": "#f5e625",
            "danger": "#f57a00",
            "light": "#F8F9FA",
            "dark": "#222222",
            "bg": "#ffffff",
            "fg": "#222222",
            "selectbg": "#aaaaaa",
            "selectfg": "#ffffff",
            "border": "#ced4da",
            "inputfg": "#565656",
            "inputbg": "#fff",
            "active": "#e5e5e5",
        },
    },
    




    "disgusting": {
        "type": "light",
        "colors": {
            "primary": "#ff007f",
            "secondary": "#3d3dff",
            "success": "#00ff00",
            "info": "#ff5733",
            "warning": "#ffd700",
            "danger": "#ff1493",
            "light": "#ffffff",
            "dark": "#000000",
            "bg": "#0f0f0f",
            "fg": "#00ffff",
            "selectbg": "#8a2be2",
            "selectfg": "#ffcc00",
            "border": "#ff69b4",
            "inputfg": "#32cd32",
            "inputbg": "#4b0082",
            "active": "#ff4500"
        },
    },







    "modern": {
        "type": "light",
        "colors": {
            "primary": "#1a73e8",
            "secondary": "#6c757d",
            "success": "#34a853",
            "info": "#2196f3",
            "warning": "#fbbc05",
            "danger": "#ea4335",
            "light": "#f5f5f5",
            "dark": "#202124",
            "bg": "#ffffff",
            "fg": "#3c4043",
            "selectbg": "#e8f0fe",
            "selectfg": "#202124",
            "border": "#dadce0",
            "inputfg": "#3c4043",
            "inputbg": "#f1f3f4",
            "active": "#e8eaed"
        },
    },




    "neon_glow": {
        "type": "dark",
        "colors": {
            "primary": "#ff006e",
            "secondary": "#8338ec",
            "success": "#3a86ff",
            "info": "#06d6a0",
            "warning": "#ffbe0b",
            "danger": "#ef233c",
            "light": "#8d99ae",
            "dark": "#1a1b27",
            "bg": "#121212",
            "fg": "#f1faee",
            "selectbg": "#ff006e",
            "selectfg": "#ffffff",
            "border": "#2b2d42",
            "inputfg": "#ffffff",
            "inputbg": "#2a2a35",
            "active": "#6a00f4"
        },
    },
    "retro_wave": {
        "type": "dark",
        "colors": {
            "primary": "#ff4d00",
            "secondary": "#7d00ff",
            "success": "#00ff99",
            "info": "#00c6ff",
            "warning": "#ffd700",
            "danger": "#ff007a",
            "light": "#ffd3e3",
            "dark": "#2d2d2d",
            "bg": "#0d0f20",
            "fg": "#e3e3e3",
            "selectbg": "#7d00ff",
            "selectfg": "#ffffff",
            "border": "#555555",
            "inputfg": "#d1d1d1",
            "inputbg": "#262626",
            "active": "#ff007a"
        },
    },
    "pastel_dream": {
        "type": "light",
        "colors": {
            "primary": "#ffb6c1",
            "secondary": "#b19cd9",
            "success": "#ace1af",
            "info": "#add8e6",
            "warning": "#ffe4b5",
            "danger": "#f08080",
            "light": "#f8f8ff",
            "dark": "#202020",
            "bg": "#fafafa",
            "fg": "#404040",
            "selectbg": "#b19cd9",
            "selectfg": "#fafafa",
            "border": "#dcdcdc",
            "inputfg": "#404040",
            "inputbg": "#f5f5f5",
            "active": "#f08080"
        },
    },
    "minimal_modern": {
        "type": "light",
        "colors": {
            "primary": "#0077b6",
            "secondary": "#0096c7",
            "success": "#02c39a",
            "info": "#00b4d8",
            "warning": "#ffba08",
            "danger": "#ef233c",
            "light": "#e9ecef",
            "dark": "#343a40",
            "bg": "#f8f9fa",
            "fg": "#212529",
            "selectbg": "#0077b6",
            "selectfg": "#ffffff",
            "border": "#dee2e6",
            "inputfg": "#212529",
            "inputbg": "#e9ecef",
            "active": "#00b4d8"
        },
    },



    "pure_black": {
        "type": "dark",
        "colors": {
            "primary": "#202020",
            "secondary": "#333333",
            "success": "#00ff00",
            "info": "#007bff",
            "warning": "#ffcc00",
            "danger": "#ff3333",
            "light": "#272727",
            "dark": "#000000",
            "bg": "#000000",
            "fg": "#ffffff",
            "selectbg": "#444444",
            "selectfg": "#ffffff",
            "border": "#555555",
            "inputfg": "#ffffff",
            "inputbg": "#1a1a1a",
            "active": "#666666"
        },
    },

    "rainbow": {
        "type": "light",
        "colors": {
            "primary": "#ff0000",
            "secondary": "#ff7f00",
            "success": "#ffff00",
            "info": "#00ff00",
            "warning": "#0000ff",
            "danger": "#4b0082",
            "light": "#9400d3",
            "dark": "#000000",
            "bg": "#ffffff",
            "fg": "#000000",
            "selectbg": "#ffd700",
            "selectfg": "#000000",
            "border": "#ff69b4",
            "inputfg": "#000000",
            "inputbg": "#ffffff",
            "active": "#ff1493"
        },
    },




    "smoothie": {
        "type": "dark",
        "colors": {
            "primary": "#2b2b2b",
            "secondary": "#383838",
            "success": "#4caf50",
            "info": "#2196f3",
            "warning": "#ffc107",
            "danger": "#f44336",
            "light": "#e6e6e6",
            "dark": "#1e1e1e",
            "bg": "#1e1e1e",
            "fg": "#d9d9d9",
            "selectbg": "#4a4a4a",
            "selectfg": "#ffffff",
            "border": "#3a3a3a",
            "inputfg": "#ffffff",
            "inputbg": "#2b2b2b",
            "active": "#5e5e5e"
        },
    },

    "cream_pastel": {
        "type": "light",
        "colors": {
            "primary": "#f5e6cc",
            "secondary": "#f8f0e3",
            "success": "#d4a373",
            "info": "#f7c6a3",
            "warning": "#f4b183",
            "danger": "#e89a9a",
            "light": "#fffaf1",
            "dark": "#cbb091",
            "bg": "#fff8e8",
            "fg": "#5b4636",
            "selectbg": "#d4b48c", 
            "selectfg": "#3e3227",
            "border": "#d6bea4",
            "inputfg": "#5b4636",
            "inputbg": "#f7e6d4",
            "active": "#bca085" 
        },
    },








    "midnight_blue": {
        "type": "dark",
        "colors": {
            "primary": "#0a1172",
            "secondary": "#1b1f3b",
            "success": "#163172",
            "info": "#26408b",
            "warning": "#3e66a1",
            "danger": "#172554",
            "light": "#f0f4fa",
            "dark": "#0a0e21",
            "bg": "#0e1621",
            "fg": "#d1d9e6",
            "selectbg": "#26408b",
            "selectfg": "#ffffff",
            "border": "#1b2735",
            "inputfg": "#d1d9e6",
            "inputbg": "#1a2331",
            "active": "#203a63"
        },
    },




    "baby_blue": {
        "type": "light",
        "colors": {
            "primary": "#a2d2ff",
            "secondary": "#caf0f8",
            "success": "#ade8f4",
            "info": "#90e0ef",
            "warning": "#48cae4",
            "danger": "#00b4d8",
            "light": "#f1f9ff",
            "dark": "#023e8a",
            "bg": "#e0f7ff",
            "fg": "#03045e",
            "selectbg": "#90e0ef",
            "selectfg": "#ffffff",
            "border": "#caf0f8",
            "inputfg": "#03045e",
            "inputbg": "#dbeeff",
            "active": "#48cae4"
        },
    },



    "blender": {
        "type": "dark",
        "colors": {
            "primary": "#d15b1f",
            "secondary": "#242424",
            "success": "#97b700",
            "info": "#64a2c8",
            "warning": "#e0aa29",
            "danger": "#b32929",
            "light": "#e5e5e5",
            "dark": "#191919",
            "bg": "#383838",
            "fg": "#e1e1e1",
            "selectbg": "#d15b1f",
            "selectfg": "#ffffff",
            "border": "#4d4d4d",
            "inputfg": "#f1f1f1",
            "inputbg": "#4d4d4d",
            "active": "#d97a37"
        },
    },



    "clown_fiesta": {
        "type": "light",
        "colors": {
            "primary": "#ff0000",
            "secondary": "#00ff00",
            "success": "#0000ff",
            "info": "#ffff00",
            "warning": "#ff00ff",
            "danger": "#00ffff",
            "light": "#ffffff",
            "dark": "#000000",
            "bg": "#ff8800",
            "fg": "#ff00aa",
            "selectbg": "#00ff88",
            "selectfg": "#0000ff",
            "border": "#ff00ff",
            "inputfg": "#ff8800",
            "inputbg": "#00ff00",
            "active": "#aa00ff"
        },
    },








    "plasticity": {
        "type": "dark",
        "colors": {
            "primary": "#6c43b8",
            "secondary": "#1e1e1e",
            "success": "#5c5c5c",
            "info": "#2c2c2c",
            "warning": "#333333",
            "danger": "#b84d4d",
            "light": "#d6d6d6",
            "dark": "#141414",
            "bg": "#1c1c1c",
            "fg": "#e0e0e0",
            "selectbg": "#6c43b8",
            "selectfg": "#ffffff",
            "border": "#2a2a2a",
            "inputfg": "#f1f1f1",
            "inputbg": "#2c2c2c",
            "active": "#845ec2"
        },
    },



    "vomit_vibes": {
        "type": "dark",
        "colors": {
            "primary": "#6b8e23",
            "secondary": "#8b4513",
            "success": "#556b2f",
            "info": "#7f6000",
            "warning": "#999900",
            "danger": "#cc9966",
            "light": "#d2b48c",
            "dark": "#3b2f2f",
            "bg": "#2f4f4f",
            "fg": "#8b0000",
            "selectbg": "#556b2f",
            "selectfg": "#ffffe0",
            "border": "#bdb76b",
            "inputfg": "#7f6000",
            "inputbg": "#8b4513",
            "active": "#808000"
        },
    },



    "radioactive_swamp": {
        "type": "dark",
        "colors": {
            "primary": "#00ff00",
            "secondary": "#008000",
            "success": "#00cc00",
            "info": "#00b300",
            "warning": "#99ff33",
            "danger": "#33cc33",
            "light": "#66ff66",
            "dark": "#004d00",
            "bg": "#003300",
            "fg": "#ccffcc",
            "selectbg": "#00ff00",
            "selectfg": "#003300",
            "border": "#006600",
            "inputfg": "#33cc33",
            "inputbg": "#004d00",
            "active": "#00cc00"
        },
    },


    "painful_pink": {
        "type": "light",
        "colors": {
            "primary": "#ff69b4",
            "secondary": "#ff1493",
            "success": "#ff85c2",
            "info": "#ffc0cb",
            "warning": "#ff00ff",
            "danger": "#ff77aa",
            "light": "#fff0f5",
            "dark": "#ff007f",
            "bg": "#ffe4e1",
            "fg": "#ff1493",
            "selectbg": "#ff69b4",
            "selectfg": "#ffe4e1",
            "border": "#ffb6c1",
            "inputfg": "#ff69b4",
            "inputbg": "#ffe4e1",
            "active": "#ff85c2"
        },
    },

    "toxic_circus": {
        "type": "dark",
        "colors": {
            "primary": "#ff00ff",
            "secondary": "#00ffff",
            "success": "#ffcc00",
            "info": "#ff0000",
            "warning": "#00ff00",
            "danger": "#0000ff",
            "light": "#ff88ff",
            "dark": "#333333",
            "bg": "#6600ff",
            "fg": "#ffff00",
            "selectbg": "#ff00ff",
            "selectfg": "#00ffff",
            "border": "#ffcc00",
            "inputfg": "#ff0000",
            "inputbg": "#ff8800",
            "active": "#ff0066"
        },
    },




    "darkly": {
        "type": "dark",
        "colors": {
            "primary": "#373737",
            "secondary": "#444444",
            "success": "#00bc8c",
            "info": "#3498db",
            "warning": "#f39c12",
            "danger": "#e74c3c",
            "light": "#ADB5BD",
            "dark": "#303030",
            "bg": "#222222",
            "fg": "#ffffff",
            "selectbg": "#555555",
            "selectfg": "#ffffff",
            "border": "#222222",
            "inputfg": "#ffffff",
            "inputbg": "#2f2f2f",
            "active": "#1F1F1F",
        },
    },
    "superhero": {
        "type": "dark",
        "colors": {
            "primary": "#4c9be8",
            "secondary": "#4e5d6c",
            "success": "#5cb85c",
            "info": "#5bc0de",
            "warning": "#f0ad4e",
            "danger": "#d9534f",
            "light": "#ABB6C2",
            "dark": "#20374C",
            "bg": "#2b3e50",
            "fg": "#ffffff",
            "selectbg": "#526170",
            "selectfg": "#ffffff",
            "border": "#222222",
            "inputfg": "#ebebeb",
            "inputbg": "#32465a",
            "active": "#2B4155",
        },
    },
    "solar": {
        "type": "dark",
        "colors": {
            "primary": "#bc951a",
            "secondary": "#94a2a4",
            "success": "#44aca4",
            "info": "#3f98d7",
            "warning": "#d05e2f",
            "danger": "#d95092",
            "light": "#A9BDBD",
            "dark": "#073642",
            "bg": "#002B36",
            "fg": "#ffffff",
            "selectbg": "#0b5162",
            "selectfg": "#ffffff",
            "border": "#00252e",
            "inputfg": "#A9BDBD",
            "inputbg": "#073642",
            "active": "#002730",
        },
    },
    "cyborg": {
        "type": "dark",
        "colors": {
            "primary": "#2a9fd6",
            "secondary": "#555555",
            "success": "#77b300",
            "info": "#9933cc",
            "warning": "#ff8800",
            "danger": "#cc0000",
            "light": "#ADAFAE",
            "dark": "#222222",
            "bg": "#060606",
            "fg": "#ffffff",
            "selectbg": "#454545",
            "selectfg": "#ffffff",
            "border": "#060606",
            "inputfg": "#ffffff",
            "inputbg": "#191919",
            "active": "#282828",
        },
    },
    "vapor": {
        "type": "dark",
        "colors": {
            "primary": "#6e40c0",
            "secondary": "#ea38b8",
            "success": "#3af180",
            "info": "#1da2f2",
            "warning": "#ffbd05",
            "danger": "#e34b54",
            "light": "#44d7e8",
            "dark": "#170229",
            "bg": "#190831",
            "fg": "#32fbe2",
            "selectbg": "#461a8a",
            "selectfg": "#ffffff",
            "border": "#060606",
            "inputfg": "#bfb6cd",
            "inputbg": "#30115e",
            "active": "#17082E",
        },
    },
    "simplex": {
        "type": "light",
        "colors": {
            "primary": "#d8220e",
            "secondary": "#858e96",
            "success": "#469307",
            "info": "#0099ce",
            "warning": "#d88220",
            "danger": "#9a479e",
            "light": "#f2f2f2",
            "dark": "#3b3d3f",
            "bg": "#fcfcfc",
            "fg": "#3b3d3f",
            "selectbg": "#a9afb6",
            "selectfg": "#ffffff",
            "border": "#858e96",
            "inputfg": "#3b3d3f",
            "inputbg": "#fcfcfc",
            "active": "#e2e2e2",
        },
    },
    "cerculean": {
        "type": "light",
        "colors": {
            "primary": "#4bb1ea",
            "secondary": "#a9b4be",
            "success": "#84b251",
            "info": "#225384",
            "warning": "#e16e25",
            "danger": "#cf3c40",
            "light": "#eceef1",
            "dark": "#33383e",
            "bg": "#ffffff",
            "fg": "#2ea4e7",
            "selectbg": "#adb5bd",
            "selectfg": "#ffffff",
            "border": "#a9b4be",
            "inputfg": "#495057",
            "inputbg": "#ffffff",
            "active": "#e5e5e5",
        },
    },
}
